debug: false
user_agent: null
cookie: null
allow_domains: null
disallow_domains: null
url_file: null
config: null
mode: Normal
max_page: 0
max_connections: 0
max_keepalive_connections: 0
max_concurrency_per_domain: null
min_request_interval: null
outfile: null
status_filter: null
proxy: null
hide_regex: false
follow_redirect: false
url: ''
detail: false
validate: false
local: null
